import { Campaign } from '../types/campaign.ts';

export const fallbackCampaigns: Campaign[] = [
  {
    name: 'Angel One NXT Demat Account',
    slug: 'angel-one-nxt',
    companyName: 'Angel One Limited',
    campaignType: 'Demat & Trading',
    description: 'Indian discount broking demat account with a mobile trading app. Charges and features are as per the provider.',
    requiredAction: 'Successful online KYC submission & Demat activation',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin verified per eligible lead post-activation',
    rules: [
      'Customer must be 18+ years with valid PAN and Aadhaar-linked mobile.',
      'Must be a new Angel One registration (no pre-existing account).',
      'Leads must be submitted within 48 hours of onboarding completion.',
    ],
    status: 'LIVE',
    isFeatured: true,
    sortOrder: 1,
  },
  {
    name: 'Upstox Pro Trading Account',
    slug: 'upstox-pro',
    companyName: 'RKSV Securities (Upstox)',
    campaignType: 'Demat & Trading',
    description: 'Investment platform with paperless account opening and charting tools, as per the provider.',
    requiredAction: 'Account opening completion & basic profile activation',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin verified upon verification of successful broker registration',
    rules: [
      'Applicant must complete full Digilocker e-Sign process.',
      'Valid Indian bank account verification required during KYC.',
    ],
    status: 'LIVE',
    isFeatured: true,
    sortOrder: 2,
  },
  {
    name: 'Choice Broking (Jiffy)',
    slug: 'choice-broking',
    companyName: 'Choice Equity Broking Pvt Ltd',
    campaignType: 'Demat & Trading',
    description: 'Full-service financial brokerage partner offering life-time free AMC options and expert equity research.',
    requiredAction: 'Digital account opening and KYC verification',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin verified per approved Demat creation',
    rules: [
      'Applicable for first-time Choice Broking users only.',
      'Pan card and bank proof mandatory.',
    ],
    status: 'LIVE',
    isFeatured: true,
    sortOrder: 3,
  },
  {
    name: 'Nirmal Bang Beyond',
    slug: 'nirmal-bang',
    companyName: 'Nirmal Bang Securities',
    campaignType: 'Demat & Trading',
    description: 'One of India’s most respected traditional brokerage houses offering customized portfolio management.',
    requiredAction: 'Online Demat onboarding with completed IPV video verification',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin verified payout upon broker account activation',
    rules: [
      'Indian resident status with active bank account.',
      'Aadhaar OTP verification required for digital sign-off.',
    ],
    status: 'LIVE',
    isFeatured: false,
    sortOrder: 4,
  },
  {
    name: 'Stocko Super App',
    slug: 'stocko-app',
    companyName: 'Stocko Financial Services',
    campaignType: 'Demat & Trading',
    description: 'Modern algorithmic and retail trading app tailored for quick execution and low-latency market depth.',
    requiredAction: 'App download, account opening, and mobile OTP verification',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin verified according to vendor validation sheet',
    rules: [
      'Available exclusively through verified partner links.',
      'Submissions subject to weekly Admin reconciliation.',
    ],
    status: 'LIVE',
    isFeatured: false,
    sortOrder: 5,
  },
  {
    name: 'Bigul Smart Investment',
    slug: 'bigul-invest',
    companyName: 'Bigul FinTech',
    campaignType: 'Demat & Trading',
    description: 'Advisory tools and trading facility for active Indian traders, as per the provider.',
    requiredAction: 'Account registration and document e-Verification',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin verified post partner portal lead submission',
    rules: [
      'First-time client registration only.',
    ],
    status: 'LIVE',
    isFeatured: false,
    sortOrder: 6,
  },
  {
    name: 'ICICI Prudential Mutual Fund',
    slug: 'icici-mutual-fund',
    companyName: 'ICICI Prudential AMC',
    campaignType: 'Mutual Funds',
    description: 'Promote diverse mutual fund portfolios and systematic investment plans (SIPs) from India’s top AMC.',
    requiredAction: 'New investor KYC & first SIP mandate setup',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin approved upon first mandate confirmation',
    rules: [
      'Applies to new mutual fund folios only.',
      'Minimum SIP tenure and mandate registration required.',
    ],
    status: 'LIVE',
    isFeatured: true,
    sortOrder: 7,
  },
  {
    name: 'Axis Mutual Fund Growth Series',
    slug: 'axis-mutual-fund',
    companyName: 'Axis Asset Management Co. Ltd',
    campaignType: 'Mutual Funds',
    description: 'High-performing equity and hybrid schemes focused on disciplined long-term compounding.',
    requiredAction: 'Online folio creation and initial investment processing',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin verified upon investment settlement',
    rules: [
      'Valid PAN, CKYC verification and Net Banking mandate.',
    ],
    status: 'LIVE',
    isFeatured: false,
    sortOrder: 8,
  },
  {
    name: 'HDFC Securities Digital Campaign',
    slug: 'hdfc-securities',
    companyName: 'HDFC Securities Ltd',
    campaignType: 'Banking & Credit',
    description: '3-in-1 integrated Demat, Trading, and HDFC Bank account ecosystem offering seamless fund movement.',
    requiredAction: 'Completion of 3-in-1 digital account opening',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin verified based on banking partner authentication',
    rules: [
      'New customer acquisition only.',
      'Must satisfy standard banking KYC guidelines.',
    ],
    status: 'LIVE',
    isFeatured: true,
    sortOrder: 9,
  },
  {
    name: '5Paisa Zero Brokerage Demat',
    slug: '5paisa-demat',
    companyName: '5paisa Capital Limited',
    campaignType: 'Demat & Trading',
    description: 'India’s pioneer in ultra-low discount broking with flat pricing and algorithmic order types.',
    requiredAction: 'Digital onboarding and successful Demat account allocation',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin verified following partner portal submission',
    rules: [
      'Aadhaar-based e-KYC must be completed 100%.',
    ],
    status: 'LIVE',
    isFeatured: false,
    sortOrder: 10,
  },
  {
    name: 'Geojit Financial Services',
    slug: 'geojit-financial',
    companyName: 'Geojit Financial Services Ltd',
    campaignType: 'Demat & Trading',
    description: 'Trusted advisory-led broking service with personalized portfolio recommendations.',
    requiredAction: 'Digital account opening and KYC verification',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin verified per verified Demat opening',
    rules: [
      'Requires active PAN and Indian residential verification.',
    ],
    status: 'PAUSED',
    isFeatured: false,
    sortOrder: 11,
  },
  {
    name: 'Motilal Oswal Wealth Creation',
    slug: 'motilal-oswal',
    companyName: 'Motilal Oswal Financial Services',
    campaignType: 'Demat & Trading',
    description: 'Award-winning research recommendations with dedicated wealth managers.',
    requiredAction: 'Complete digital onboarding and risk profiling',
    payout: null,
    currency: 'INR',
    payoutTerms: 'Admin verified upon Demat activation',
    rules: [
      'Applicable for new client registrations only.',
    ],
    status: 'LIVE',
    isFeatured: false,
    sortOrder: 12,
  },
];
