import React, { useEffect, useState } from 'react';
import { Wallet, Search, ShieldCheck, Eye, Check, X, Clock3, ArrowRight, FileCheck2, LockKeyhole } from 'lucide-react';

export interface WithdrawalFilters { search: string; status: string; paymentMethod: string; startDate: string; endDate: string; page: number; }
export const defaultWithdrawalFilters: WithdrawalFilters = { search: '', status: 'ALL', paymentMethod: 'ALL', startDate: '', endDate: '', page: 1 };
const input = 'min-w-0 w-full rounded-lg border border-[#234263] bg-[#091425] px-3 py-2.5 text-xs text-slate-200 outline-none focus:border-sky-400';
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(value);
const date = (value?: string) => value ? new Date(value).toLocaleString() : '—';
const statusStyles: Record<string, string> = { PENDING: 'border-amber-400/30 bg-amber-400/10 text-amber-200', PROCESSING: 'border-sky-400/30 bg-sky-400/10 text-sky-200', APPROVED: 'border-violet-400/30 bg-violet-400/10 text-violet-200', PAID: 'border-emerald-400/30 bg-emerald-400/10 text-emerald-200', PROCESSED: 'border-emerald-400/30 bg-emerald-400/10 text-emerald-200', REJECTED: 'border-rose-400/30 bg-rose-400/10 text-rose-200', CANCELLED: 'border-slate-400/30 bg-slate-400/10 text-slate-200' };

export const AdminWithdrawals: React.FC<{ response: any; filters: WithdrawalFilters; busy: boolean; onFilters: (filters: WithdrawalFilters) => void; onAction: (path: string, body: Record<string, string>) => void }> = ({ response, filters, busy, onFilters, onAction }) => {
  const [draft, setDraft] = useState(filters);
  const [selected, setSelected] = useState<any>(null);
  const [decision, setDecision] = useState<{ item: any; status: string } | null>(null);
  const [reason, setReason] = useState('');
  useEffect(() => { setDraft(filters); }, [filters]);
  useEffect(() => { if (selected) setSelected(response?.data?.find((item: any) => item._id === selected._id) || selected); }, [response]);
  const records: any[] = Array.isArray(response?.data) ? response.data : [];
  const action = (item: any, status: string) => { setReason(''); setDecision({ item, status }); };
  const actions = (item: any) => <div className="flex flex-wrap gap-1.5">
    {item.status === 'PENDING' && <button disabled={busy} onClick={() => onAction(`/admin/withdrawals/${item._id}`, { status: 'PROCESSING' })} className="rounded-md border border-sky-700 px-2.5 py-1.5 text-[11px] text-sky-200 disabled:opacity-40">Process</button>}
    {['PENDING', 'PROCESSING'].includes(item.status) && <button disabled={busy} onClick={() => action(item, 'APPROVED')} className="flex items-center gap-1 rounded-md border border-emerald-700 bg-emerald-500/10 px-2.5 py-1.5 text-[11px] text-emerald-200 disabled:opacity-40"><Check className="h-3 w-3" />Approve</button>}
    {['PENDING', 'PROCESSING', 'APPROVED'].includes(item.status) && <button disabled={busy} onClick={() => action(item, 'REJECTED')} className="flex items-center gap-1 rounded-md border border-rose-800 px-2.5 py-1.5 text-[11px] text-rose-300 disabled:opacity-40"><X className="h-3 w-3" />Reject</button>}
    {['PROCESSING', 'APPROVED'].includes(item.status) && <button disabled={busy} onClick={() => action(item, 'PAID')} className="rounded-md border border-emerald-700 bg-emerald-500/10 px-2.5 py-1.5 text-[11px] text-emerald-200 disabled:opacity-40">Mark paid</button>}
    <button onClick={() => setSelected(item)} className="flex items-center gap-1 rounded-md border border-[#234263] px-2.5 py-1.5 text-[11px] text-slate-300"><Eye className="h-3 w-3" />View</button>
  </div>;
  const badge = (item: any) => <span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-semibold ${statusStyles[item.status] || statusStyles.CANCELLED}`}>{item.status}</span>;
  const close = () => { setSelected(null); setDecision(null); };
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === 'Escape' && !busy) close(); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [busy]);
  return <div className="space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="rounded-xl border border-sky-500/20 bg-sky-500/10 p-3 text-sky-300"><Wallet className="h-6 w-6" /></span><div><h2 className="text-2xl font-bold">Withdrawals</h2><p className="mt-1 text-xs text-slate-400">Review and manage partner payout requests.</p></div></div><span className="flex items-center gap-2 rounded-lg border border-emerald-600/25 bg-emerald-500/5 px-3 py-2 text-[11px] text-emerald-300"><ShieldCheck className="h-4 w-4" />Admin authorization required</span></header>
    <form className="grid gap-3 rounded-xl border border-[#203755] bg-[#0d192b] p-4 sm:grid-cols-2 lg:grid-cols-[2fr_1fr_1fr_1fr_1fr_auto]" onSubmit={(event) => { event.preventDefault(); onFilters({ ...draft, page: 1 }); }}>
      <label className="relative sm:col-span-2 lg:col-span-1"><span className="sr-only">Search withdrawals</span><Search className="absolute left-3 top-3 h-4 w-4 text-sky-400" /><input className={`${input} pl-9`} placeholder="Name, email, UPI or transaction ID" value={draft.search} onChange={(event) => setDraft({ ...draft, search: event.target.value })} /></label>
      <label><span className="sr-only">Withdrawal status</span><select className={input} value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value })}><option value="ALL">All statuses</option>{Object.keys(statusStyles).map((status) => <option key={status}>{status}</option>)}</select></label>
      <label><span className="sr-only">Payment method</span><select className={input} value={draft.paymentMethod} onChange={(event) => setDraft({ ...draft, paymentMethod: event.target.value })}><option value="ALL">All methods</option><option value="UPI">UPI</option><option value="BANK_TRANSFER">Bank transfer</option></select></label>
      <label className="text-[10px] text-slate-400">Requested from<input type="date" className={`${input} mt-1`} value={draft.startDate} max={draft.endDate || undefined} onChange={(event) => setDraft({ ...draft, startDate: event.target.value })} /></label><label className="text-[10px] text-slate-400">Requested until<input type="date" className={`${input} mt-1`} value={draft.endDate} min={draft.startDate || undefined} onChange={(event) => setDraft({ ...draft, endDate: event.target.value })} /></label>
      <button disabled={busy} className="self-end rounded-lg bg-sky-500 px-5 py-2.5 text-xs font-semibold text-[#06101f] hover:bg-sky-400 disabled:opacity-40">Apply</button>
    </form>
    <div className="overflow-hidden rounded-xl border border-[#203755] bg-gradient-to-br from-[#0f2038] to-[#091323]">
      <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[980px] text-left text-xs"><thead className="border-b border-[#234263] bg-[#0a1628] text-[10px] uppercase tracking-wide text-slate-400"><tr>{['#', 'Partner', 'Email / Destination', 'Amount', 'Method', 'Status', 'Requested', 'Last updated', 'Actions'].map((label) => <th key={label} className="px-4 py-4 font-medium">{label}</th>)}</tr></thead><tbody>{records.map((item, index) => <tr key={item._id} className="border-b border-[#203755]/70 align-top hover:bg-sky-500/5"><td className="px-4 py-5 text-slate-500">{((response?.page || 1) - 1) * 20 + index + 1}</td><td className="px-4 py-5"><p className="font-semibold text-white">{item.partner?.fullName || 'Partner'}</p><p className="mt-1 text-[10px] text-slate-400">{item.partnerId}</p></td><td className="max-w-52 break-all px-4 py-5"><p className="text-slate-300">{item.partner?.email || '—'}</p><p className="mt-1 text-[10px] text-sky-300">{item.payoutDestination || '—'}</p></td><td className="whitespace-nowrap px-4 py-5 font-bold text-white">{money(item.amount)}</td><td className="px-4 py-5 text-sky-300">{item.paymentMethod === 'BANK_TRANSFER' ? 'Bank transfer' : 'UPI'}</td><td className="px-4 py-5">{badge(item)}</td><td className="px-4 py-5 text-[10px] text-slate-400">{date(item.createdAt)}</td><td className="px-4 py-5 text-[10px] text-slate-400">{date(item.updatedAt)}</td><td className="min-w-40 px-4 py-5">{actions(item)}</td></tr>)}</tbody></table></div>
      <div className="divide-y divide-[#203755] md:hidden">{records.map((item) => <section key={item._id} className="space-y-3 p-4"><div className="flex justify-between gap-3"><div><p className="text-sm font-semibold">{item.partner?.fullName || item.partnerId}</p><p className="mt-1 text-[10px] text-slate-400">{item.partnerId}</p></div><p className="font-bold text-sky-200">{money(item.amount)}</p></div><p className="break-all text-xs text-slate-300">{item.partner?.email} · {item.payoutDestination}</p><div className="flex flex-wrap items-center gap-3">{badge(item)}<span className="text-[10px] text-slate-400">{item.paymentMethod === 'BANK_TRANSFER' ? 'Bank transfer' : 'UPI'} · {date(item.createdAt)}</span></div>{actions(item)}</section>)}</div>
      {records.length === 0 && <div className="px-6 py-14 text-center"><Wallet className="mx-auto mb-3 h-8 w-8 text-slate-500" /><p className="text-sm font-semibold text-slate-200">No withdrawal requests found</p><p className="mt-1 text-xs text-slate-500">Try changing your filters or check back for new requests.</p></div>}
      <div className="flex items-center justify-between gap-3 px-4 py-3 text-[11px] text-slate-400"><span>{response?.total ?? records.length} requests · Page {response?.page || 1} of {response?.totalPages || 1}</span><div className="flex gap-2"><button disabled={busy || (response?.page || 1) <= 1} onClick={() => onFilters({ ...filters, page: filters.page - 1 })} className="rounded border border-[#234263] px-3 py-1.5 disabled:opacity-30">Previous</button><button disabled={busy || (response?.page || 1) >= (response?.totalPages || 1)} onClick={() => onFilters({ ...filters, page: filters.page + 1 })} className="rounded border border-[#234263] px-3 py-1.5 disabled:opacity-30">Next</button></div></div>
    </div>
    <div className="grid gap-4 rounded-xl border border-[#203755] bg-[#0d192b] p-4 sm:grid-cols-3">{[{ icon: LockKeyhole, title: 'Admin approval', text: 'Every request follows a review workflow.' }, { icon: Clock3, title: 'Payment references', text: 'A reference is required to mark a payout paid.' }, { icon: FileCheck2, title: 'Audit history', text: 'Withdrawal decisions are recorded.' }].map(({ icon: Icon, title, text }) => <div key={title} className="flex gap-3"><Icon className="h-6 w-6 shrink-0 text-cyan-300" /><div><p className="text-xs font-semibold">{title}</p><p className="mt-1 text-[10px] leading-4 text-slate-400">{text}</p></div></div>)}</div>
    {(selected || decision) && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm" onClick={() => { if (!busy) close(); }}><section role="dialog" aria-modal="true" aria-labelledby="withdrawal-dialog-title" className="max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-[#234263] bg-[#101d31] p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="mb-5 flex justify-between gap-3"><h3 id="withdrawal-dialog-title" className="text-lg font-semibold">{decision ? `${decision.status === 'PAID' ? 'Record payment' : decision.status === 'REJECTED' ? 'Reject withdrawal' : 'Approve withdrawal'}` : 'Withdrawal details'}</h3><button disabled={busy} onClick={close} aria-label="Close withdrawal dialog"><X className="h-5 w-5 text-slate-400" /></button></div>
      {decision ? <form onSubmit={(event) => { event.preventDefault(); onAction(`/admin/withdrawals/${decision.item._id}`, { status: decision.status, ...(decision.status === 'PAID' ? { paymentReference: reason.trim() } : decision.status === 'REJECTED' ? { internalNote: reason.trim() } : {}) }); setDecision(null); }}><p className="mb-4 text-sm text-slate-300">{money(decision.item.amount)} · {decision.item.partner?.fullName || decision.item.partnerId}</p>{decision.status !== 'APPROVED' && <label className="block text-xs text-slate-400">{decision.status === 'PAID' ? 'Payment reference' : 'Rejection reason'}<input autoFocus required maxLength={decision.status === 'PAID' ? 160 : 2000} className={`${input} mt-2`} value={reason} onChange={(event) => setReason(event.target.value)} pattern=".*\S.*" /></label>}<p className="mt-4 text-[11px] leading-5 text-slate-400">{decision.status === 'PAID' ? 'Record the reference after you have completed the payment to the partner.' : 'This decision will be saved in the withdrawal audit history.'}</p><button disabled={busy} className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-sky-500 py-3 text-sm font-semibold text-[#06101f]">Confirm<ArrowRight className="h-4 w-4" /></button></form> : <dl className="space-y-3 text-xs">{[['Partner', selected.partner?.fullName || selected.partnerId], ['Email', selected.partner?.email], ['Transaction ID', selected.transactionId], ['Amount', money(selected.amount)], ['Method', selected.paymentMethod], ['Destination', selected.payoutDestination], ['Status', selected.status], ['Requested', date(selected.createdAt)], ['Last updated', date(selected.updatedAt)], ['Payment reference', selected.paymentReference], ['Admin note', selected.internalNote]].map(([label, value]) => <div key={label} className="grid grid-cols-[110px_1fr] gap-3 border-b border-[#234263]/60 pb-2"><dt className="text-slate-400">{label}</dt><dd className="break-all text-slate-200">{value || '—'}</dd></div>)}</dl>}
    </section></div>}
  </div>;
};
