import { ICampaign } from '../types/index.ts';

export const initialCampaignSeeds: ICampaign[] = [
  {
    name: 'Angel One NXT Demat Account',
    slug: 'angel-one-nxt',
    companyName: 'Angel One Limited',
    campaignType: 'Demat & Trading',
    description: 'Premier Indian discount broking demat account with advanced smart API access, zero delivery charges, and intuitive mobile app.',
    requiredAction: 'Successful online KYC submission & Demat activation',
    payout: 450,
    currency: 'INR',
    payoutTerms: 'Admin verified per eligible lead post-activation',
    rules: [
      'Customer must be 18+ years with valid PAN and Aadhaar-linked mobile.',
      'Must be a new Angel One registration (no pre-existing account).',
      'Leads must be submitted within 48 hours of onboarding completion.',
      'Self-referrals and duplicate PAN submissions will be rejected.',
    ],
    status: 'LIVE',
    logoUrl: '/logos/angelone.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/angelone/v1',
    isFeatured: true,
    sortOrder: 1,
  },
  {
    name: 'Upstox Pro Trading Account',
    slug: 'upstox-pro',
    companyName: 'RKSV Securities (Upstox)',
    campaignType: 'Demat & Trading',
    description: 'Next-generation investment platform featuring instant paperless account opening, TradingView charting, and zero maintenance fee options.',
    requiredAction: 'Account opening completion & basic profile activation',
    payout: 500,
    currency: 'INR',
    payoutTerms: 'Admin verified upon verification of successful broker registration',
    rules: [
      'Applicant must complete full Digilocker e-Sign process.',
      'Valid Indian bank account verification required during KYC.',
      'Lead status remains Pending until Admin cross-checks with Upstox report.',
    ],
    status: 'LIVE',
    logoUrl: '/logos/upstox.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/upstox/v1',
    isFeatured: true,
    sortOrder: 2,
  },
  {
    name: 'Choice Broking (Jiffy)',
    slug: 'choice-broking',
    companyName: 'Choice Equity Broking Pvt Ltd',
    campaignType: 'Demat & Trading',
    description: 'Full-service financial brokerage partner offering life-time free AMC options, expert equity research, and dedicated relationship manager.',
    requiredAction: 'Digital account opening and KYC verification',
    payout: 400,
    currency: 'INR',
    payoutTerms: 'Admin verified per approved Demat creation',
    rules: [
      'Applicable for first-time Choice Broking users only.',
      'Pan card and bank proof mandatory.',
      'Admin retains full authority to approve or reject based on vendor logs.',
    ],
    status: 'LIVE',
    logoUrl: '/logos/choice.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/choice/v1',
    isFeatured: false,
    sortOrder: 3,
  },
  {
    name: 'Nirmal Bang Beyond',
    slug: 'nirmal-bang',
    companyName: 'Nirmal Bang Securities',
    campaignType: 'Demat & Trading',
    description: 'Trusted institutional legacy broker providing comprehensive wealth advisory, commodity trading, and customized research calls.',
    requiredAction: 'Demat account opening & document verification',
    payout: 350,
    currency: 'INR',
    payoutTerms: 'Disbursed upon completion of compliance audit',
    rules: [
      'Only leads with active PAN and valid bank mandate considered.',
      'Lead verification cycle takes approximately 3-5 business days.',
    ],
    status: 'LIVE',
    logoUrl: '/logos/nirmalbang.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/nirmalbang/v1',
    isFeatured: false,
    sortOrder: 4,
  },
  {
    name: 'Stocko Super App',
    slug: 'stocko-app',
    companyName: 'GCL Securities Limited',
    campaignType: 'Demat & Trading',
    description: 'High-speed algorithmic trading engine and mobile terminal tailored for active intraday traders and derivatives investors.',
    requiredAction: 'Account registration and e-Sign submission',
    payout: 300,
    currency: 'INR',
    payoutTerms: 'Payable post confirmation of active trading account setup',
    rules: [
      'Duplicate lead submissions will trigger account flag.',
      'Lead must include matching customer contact details.',
    ],
    status: 'LIVE',
    logoUrl: '/logos/stocko.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/stocko/v1',
    isFeatured: false,
    sortOrder: 5,
  },
  {
    name: 'HDFC Sky All-in-One App',
    slug: 'hdfc-sky',
    companyName: 'HDFC Securities Limited',
    campaignType: 'Demat & Trading',
    description: 'Direct access to Indian equities, US stocks, mutual funds, and digital gold from India’s most trusted banking brand.',
    requiredAction: 'Online Demat registration & Aadhaar verification',
    payout: 550,
    currency: 'INR',
    payoutTerms: 'Standard verified affiliate commission released upon broker clearance',
    rules: [
      'Direct tie-up program: strict anti-fraud checks enforced.',
      'Customer must complete OTP verification on Aadhaar mobile.',
    ],
    status: 'LIVE',
    logoUrl: '/logos/hdfcsky.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/hdfcsky/v1',
    isFeatured: true,
    sortOrder: 6,
  },
  {
    name: 'ICICI Direct Prime',
    slug: 'icici-direct',
    companyName: 'ICICI Securities Limited',
    campaignType: 'Banking & Credit',
    description: 'Integrated 3-in-1 account combining ICICI Bank savings, trading, and demat accounts with instant liquidity transfer features.',
    requiredAction: '3-in-1 Account setup and instant mandate activation',
    payout: 600,
    currency: 'INR',
    payoutTerms: 'Admin verification required against bank onboarding feed',
    rules: [
      'Account holder must not hold existing active ICICI Direct portfolio.',
      'Minimum initial fund transfer of ₹100 required for activation.',
    ],
    status: 'LIVE',
    logoUrl: '/logos/icicidirect.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/icicidirect/v1',
    isFeatured: true,
    sortOrder: 7,
  },
  {
    name: 'Motilal Oswal Financial Services',
    slug: 'motilal-oswal',
    companyName: 'Motilal Oswal Securities Limited',
    campaignType: 'Demat & Trading',
    description: '30+ years of wealth creation expertise with award-winning research recommendations and dedicated personal portfolio advisor.',
    requiredAction: 'Investor Demat creation and KYC completion',
    payout: 500,
    currency: 'INR',
    payoutTerms: 'Verified weekly by Admin upon receiving broker activation sheets',
    rules: [
      'Customer must submit original signature and PAN image.',
      'Incomplete KYC attempts will be marked as Rejected by Admin.',
    ],
    status: 'LIVE',
    logoUrl: '/logos/motilaloswal.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/motilaloswal/v1',
    isFeatured: false,
    sortOrder: 8,
  },
  {
    name: 'SBI Securities Smart Invest',
    slug: 'sbi-securities',
    companyName: 'SBICAP Securities Limited',
    campaignType: 'Banking & Credit',
    description: 'Backed by State Bank of India, delivering utmost security, pan-India branch assistance, and competitive brokerage tiers.',
    requiredAction: 'Digital onboarding & Demat setup via YONO/Online',
    payout: 400,
    currency: 'INR',
    payoutTerms: 'Payable per approved account confirmed in official MIS',
    rules: [
      'Lead details must match SBI customer verification database.',
      'Verification conducted manually by Admin against weekly reports.',
    ],
    status: 'LIVE',
    logoUrl: '/logos/sbisecurities.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/sbisecurities/v1',
    isFeatured: false,
    sortOrder: 9,
  },
  {
    name: 'Kotak Cherry Mutual Funds',
    slug: 'kotak-cherry',
    companyName: 'Kotak Mahindra Group',
    campaignType: 'Mutual Funds',
    description: 'Curated wealth baskets, direct mutual funds, bonds, and fixed deposits in one clean, zero-commission investing application.',
    requiredAction: 'App install, KYC setup and initial SIP / Lumpsum registration',
    payout: 300,
    currency: 'INR',
    payoutTerms: 'Commission credited upon verification of first transaction confirmation',
    rules: [
      'Mutual fund KYC compliance is mandatory.',
      'First investment of minimum ₹500 required for partner qualification.',
    ],
    status: 'LIVE',
    logoUrl: '/logos/kotakcherry.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/kotakcherry/v1',
    isFeatured: false,
    sortOrder: 10,
  },
  {
    name: 'Dhan App (Raise Financial)',
    slug: 'dhan-app',
    companyName: 'Moneylicious Securities Pvt Ltd',
    campaignType: 'Demat & Trading',
    description: 'Made for Super Traders: Trade directly from TradingView charts, lightning-fast order execution, and advanced strategy builder tools.',
    requiredAction: 'Paperless Demat account opening & verification',
    payout: 450,
    currency: 'INR',
    payoutTerms: 'Admin verification following electronic confirmation from Dhan',
    rules: [
      'User must complete full camera live-photo and PAN KYC.',
      'Fast track verification available for leads with clean documentation.',
    ],
    status: 'LIVE',
    logoUrl: '/logos/dhan.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/dhan/v1',
    isFeatured: false,
    sortOrder: 11,
  },
  {
    name: '5Paisa Discount Broking',
    slug: '5paisa-broking',
    companyName: '5paisa Capital Limited',
    campaignType: 'Demat & Trading',
    description: 'Ultra-low cost flat ₹20 brokerage, robo-advisory tools, auto-investing features, and instant Demat account activation.',
    requiredAction: 'Online account opening & verification',
    payout: 350,
    currency: 'INR',
    payoutTerms: 'Disbursed upon account creation confirmation',
    rules: [
      'Valid for new Indian citizens with mobile linked Aadhaar.',
      'Subject to Admin confirmation against vendor transaction logs.',
    ],
    status: 'PAUSED', // Paused campaign for status testing
    logoUrl: '/logos/5paisa.svg',
    baseTrackingUrl: 'https://internal-tracking.vedafl.com/5paisa/v1',
    isFeatured: false,
    sortOrder: 12,
  },
];
